language: node_js
node_js:
  - 12.6.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
  - "/^feature.*$/"
  - "/^release.*$/"
  - "/^hotfix.*$/"
before_script:  npm install && node slack-notifications/travis-before_script.js
script: npm test
before_deploy: npm install now@16.7.3 --no-save && node slack-notifications/travis-before_deploy.js
deploy:
- provider: script
  script: now -f --local-config=now-stage.json --scope ibcol --token $NOW_TOKEN -e TRAVIS_BUILD_WEB_URL -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_ID -e TRAVIS_REPO_SLUG -e TRAVIS_COMMIT_RANGE -e TRAVIS_COMMIT -e TRAVIS > NOW_URL.log
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature.*"
- provider: script
  script: now -f --local-config=now-production.json --scope ibcol --token $NOW_TOKEN -e TRAVIS_BUILD_WEB_URL -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_ID -e TRAVIS_REPO_SLUG -e TRAVIS_COMMIT_RANGE -e TRAVIS_COMMIT -e TRAVIS > NOW_URL.log
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^release.*|^hotfix.*"
- provider: script
  script: now -f --local-config=now-stage.json --scope ibcol --token $NOW_TOKEN -e TRAVIS_BUILD_WEB_URL -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_ID -e TRAVIS_REPO_SLUG -e TRAVIS_COMMIT_RANGE -e TRAVIS_COMMIT -e TRAVIS > NOW_URL.log --prod && cat NOW_URL.log && node slack-notifications/now-alias.js https://www.uat.ibcol.org
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: dev
- provider: script
  script: now -f --local-config=now-production.json --scope ibcol --token $NOW_TOKEN -e TRAVIS_BUILD_WEB_URL -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_ID -e TRAVIS_REPO_SLUG -e TRAVIS_COMMIT_RANGE -e TRAVIS_COMMIT -e TRAVIS > NOW_URL.log --prod && node slack-notifications/now-alias.js https://www.ibcol.org
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: master
env:
  global:
    secure: kzh4kj/eMyrmXdvfpwzyurZ5rVYqlz4TKfp16ZNF6ylCysE+iB9DJkJKBLHGpby8Ool0vEsZPH57Ks676ErmobqeyfRGRNFa5aIo7JM48ZnCofxSMOsIaoBzET90OhC7+SoaveRcubQpXX+6kHgLYGoDhiJtKcV6+481TnvtUcHMu47A0eo1OI9xG8mkAzNsZQtMPHKXyh2eevKI6sCKvaXYp8XAY/50kRlyLXqS7CXTkPkumfRI7XVXb/0/q3rOPnQuSiyLfqUQ0SJDx4Lrp3lBTSII5ovb3B1IasU/u5RnyUK+UQbnWlF2MItr3sNc4vGEXnGWifzfzUbWBo0CziQNijP4J8U6XFZGjywjDY2IaA5F9B9Ft/CrrUGB4iOY+AJY6Ayd5V2W39M0o7uQ2tmw4qnphcWFJIiNz4SnfxxJ8dEsSSXKS8QtIkZ3iaF0dHHc/NjNWC3vkNfLOeer/1ebt04UGMLVMH+DA3RiyFCNnAZ+zcHJf8jLIMcSq04tijAwoLiANo6jROh24/1AqN24/4e9TQ1Dde0JIwgdaDyU/vv9GOI/UwFt6WVlWWdi1DLCboRPwx0LohH/h55kCtsjtlvTpongAfAbTr2pJ1lLxw9oJ2dz8kVE8q4/uDHlICDlzkVq+ew11AQROtcA9Rb+Z88PgKAHKA55r+a5utA=
after_deploy: echo $(cat NOW_URL.log)
notifications:
  slack:
    rooms:
      - ibcol:wfsCwWk3PUbhMxwaVoCcuXHc#web-dev
